site_name: Data Computation Part 1
site_description: Cloud Computing, Virtualisation, Containers & Orchestration
site_url: https://supaerodatascience.github.io/OBD/2_data_computation/
site_dir: ../site/
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: blue
    accent: blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/OBD/master/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/OBD/master/favicon.ico'
  features:
    - toc.autohide

repo_name: SupaeroDataScience/OBD
repo_url: https://github.com/SupaeroDataScience/OBD

nav:
- Overview: index.md
- Introduction: 1_intro.md
- Cloud Computing:
  - Lectures: 2_cloud.md
  - TP 1 GCP Initial Setup & First Steps : exercises/1_gcp_setup.md
  - TP 2 GCP Hands On: exercises/2_gcp_handson.md
- Containers, Docker:
  - Lecture: 3_containers.md
  - TP: exercises/3_docker.md
- Orchestration, Deployment, Kubernetes:
  - Lecture: 4_orchestration.md
  - Interactive Hands On: 5_deployment.md 
  - TP: exercises/5_bonus.md
- Bureau d'Etudes: exercises/4_be.md
- Conclusion: 6_conclusion.md
- Reading List: 7_readings.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: 🔗
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
